name: swipable_stack
description: A widget for stacking cards, which users can swipe horizontally and vertically with beautiful animations.
version: 0.1.1
homepage: https://github.com/HeavenOSK/flutter_swipable_stack
environment:
  sdk: ">=2.10.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

